stages:
    - test
    - build
    - deploy

analyze:
    stage: test
    image:
        name: ghcr.io/phpstan/phpstan:latest
        entrypoint: [ "" ]
    before_script:
        - composer config --global  cache-dir $PWD/.composer
        - composer install
    script:
        - phpstan analyse
    cache:
        key: "package_$CI_COMMIT_BRANCH"
        paths:
            - .composer

unit:
    stage: test
    image: thecodingmachine/php:8.0-v4-cli
    artifacts:
        when: always
        reports:
            junit: phpunit-report.xml
    before_script:
        - composer config --global  cache-dir $PWD/.composer
        - composer install
    script:
        - phpunit tests --log-junit phpunit-report.xml
    cache:
        key: "package_$CI_COMMIT_BRANCH"
        paths:
            - .composer

build:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [ "" ]
    script:
        - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$REPOSITORY_URL\":\"ecr-login\"}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination "$REPOSITORY_URL/$ECR_REPOSITORY:$CI_COMMIT_SHA"
    only:
        - master

deploy:
    stage: deploy
    image:
        name: amazon/aws-cli
        entrypoint: [ "" ]
    script:
        - aws ssm put-parameter --name "$VERSION_PATH" --value "$CI_COMMIT_SHA" --overwrite --type String
        - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://git.simplia.cz/api/v4/projects/902/trigger/pipeline
    environment:
        name: production
    only:
        - master
